### PR TITLE
Add Mynerve

### PR DESCRIPTION
**Pull request by emmamarichal**
Hi @carolinashort,

I hope you're well.

I reviewed your font and exported it, I have nothing to say, everything is great!
I just changed the name as agreed (it is now Mynerve). I tested it and everything works fine, it's perfect!

I'm attaching the QA if you want to check on your side that everything is ok.
[QA_Mynerve.zip](https://github.com/carolinashort/MyNerve/files/10140648/QA_Mynerve.zip)

cheers!

### CODE REVIEW

**Comment by carolinashort** [comment]
Hi @emmamarichal! 
I hope you're well too! Thanks for your review, I see a couple of minor minor issues, do you mind if I fix them? Spacing mainly, I see you've fix aring and ë, but there are some other little details.

**Comment by emmamarichal** [comment]
@carolinashort Yes of course, take your time, I'll export the fonts again thursday or friday :) And don't hesitate if you need more time to check!

**Comment by emmamarichal** [comment]
Hi @carolinashort!
I hope you're well.
Could you ping me here when the sources are ready? :)

**Comment by carolinashort** [comment]
Hi @emmamarichal Emma, thanks for the heads up! It's ready now. Let me know if I've missed sth.

**Comment by emmamarichal** [comment]
@carolinashort Thanks you, I'll work on it friday :)

**Pull request merged**
